# Generated by Django 4.1.3 on 2022-11-26 20:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=50, verbose_name="Full name")),
                ("avatar", models.CharField(max_length=500, verbose_name="Profile photo URL")),
                ("contact", models.CharField(max_length=50, verbose_name="User's contact info")),
                ("about", models.TextField(blank=True)),
                ("latitude", models.DecimalField(decimal_places=7, default=Decimal("0.0"), max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=7, default=Decimal("0.0"), max_digits=9)),
                ("disliked", models.ManyToManyField(blank=True, related_name="disliked_by", to="api.userprofile")),
                ("liked", models.ManyToManyField(blank=True, related_name="liked_by", to="api.userprofile")),
                ("matched", models.ManyToManyField(blank=True, related_name="matched_related", to="api.userprofile")),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
